### PR TITLE
Fix Cloning 2Dtemplate model, fix units in some functions

### PR DESCRIPTION
**Pull request by henrikef**
Fixed the issue where map information was lost when cloning a 2D template function instance. As suggested by @giacomov , the path to the fits file is saved rather than the map itself. So, the user needs to make sure that the fits file is still available when the model is cloned or loaded from a yml file.

Also added some more tests for functions (made sure they return the same value after being cloned) and made all functions calls work with and without units so all current tests pass.

### CODE REVIEW

**Comment by henrikef** [comment]
Not sure what's going on with the macos test: 

https://travis-ci.org/giacomov/astromodels/jobs/457176182#L1179

```
import: 'astromodels.xspec'
Traceback (most recent call last):
  File "/Users/travis/miniconda/conda-bld/astromodels_1542663534997/test_tmp/run_test.py", line 20, in <module>
    import astromodels.xspec
  File "/Users/travis/miniconda/conda-bld/astromodels_1542663534997/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python2.7/site-packages/astromodels/xspec/__init__.py", line 1, in <module>
    from .factory import *
  File "/Users/travis/miniconda/conda-bld/astromodels_1542663534997/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python2.7/site-packages/astromodels/xspec/factory.py", line 17, in <module>
    from astromodels.xspec import _xspec
ImportError: dlopen(/Users/travis/miniconda/conda-bld/astromodels_1542663534997/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python2.7/site-packages/astromodels/xspec/_xspec.so, 2): Library not loaded: @rpath/libwcs.5.18.dylib
  Referenced from: /Users/travis/miniconda/conda-bld/astromodels_1542663534997/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libXSFunctions.dylib
  Reason: image not found
```

**Comment by henrikef** [comment]
The  test_geminga_paper test for HAL fails with these changes for some reason, I am looking into it.

**Comment by giacomov** [comment]
ok. Regarding the Mac OSX, it is broken at the moment. One package `wcslib` was updated and it breaks on other package (`xspec-modelsonly`) only on Mac. Don't worry about that for the moment, I am working to fix this and many other problems regarding versioning.

**Comment by giacomov** [comment]
This is an interesting corner case.

I think it should still be possible to compute the TS. There are two options:

* Unlink the linked parameters momentarily, compute the TS, then link them back
* Fix the parameter linked to the parameter of the source we are removing to the best fit, compute the TS, then free it again

Thoughts?

**Comment by henrikef** [comment]
Both options sound reasonable (and I could try to implement both and let the user choose) but will we still have nested models in those cases? I guess we could still calculate the TS and print a warning that Wilks' theorem does not apply?

**Comment by henrikef** [comment]
Also, do you have a preference whether the 'unlinking' should be implemented in astromodels (remove_source()) or 3ML (compute_TS() )?

**Comment by giacomov** [comment]
I believe it should be in `remove_source` in `astromodels`.

I think the first approach (removing the link and treating the linked parameter as free) is better because the other one removes one degree of freedom from the fit. But I agree that we should print a warning.

Let me merge this PR first. Then, please open a new one with the fix of `remove_source`.

Thanks!

**Pull request merged**
