### PR TITLE
added cosine prior for angular functions

### PR DESCRIPTION
**Pull request by grburgess**
Implements a cosine prior that has equal probability over angle

### CODE REVIEW

**Comment by grburgess** [comment]
errr. I believe the units are failing because this is intended to be an angular function so when units get introduced, the numpy functions start throwing errors. Would it be ok to explicitly set the x units to unit less @giacomov ?

**Comment by giacomov** [comment]
Yes, 
we can make the test smarter.

You can declare the new function as having fixed units like the XSpec functions. Then we can fix the test so that it checks if the function to be tested has fixed units and if yes, it uses those.

Have a look at the code you have under ~/.astromodels/data for one of the XSpec functions, and make the new prior having fixed units. Then have the test check for fixed units and if yes use those.

I could do it but it is faster if you do.

**Comment by grburgess** [comment]
Will do!

**Comment by grburgess** [comment]
@giacomov the problem is a little deeper than in fixed_units. We would have to change how point sources work to test this function OR look for dimensionless fixed units in x_unit during the tests and skip them. I can do the latter, but the former should be examined by you.

**Pull request merged**
