### PR TITLE
adding lookup for macports gfortran

### PR DESCRIPTION
**Pull request by grburgess**
To fix Nora's problem with gfortran installed via MacPorts

### CODE REVIEW

**Comment by grburgess** [comment]
I added the possibility to to set GFORTRAN_LIB as an environment variable. This way if it is not installing we do not have to keep adding custom paths.

**Comment by giacomov** [comment]
I am reverting this. 

The setup code had become ugly and it doesn't work for a normal unix installation.

It fails with:
```
Processing /home/giacomov/develop/astromodels
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-KwXT0H-build/setup.py", line 294, in <module>
        ext_modules_configuration = setup_xspec()
      File "/tmp/pip-KwXT0H-build/setup.py", line 188, in setup_xspec
        env_var_gfortran_lib = os.environ['GFORTRAN_LIB']
      File "/home/giacomov/work_env/lib/python2.7/UserDict.py", line 40, in __getitem__
        raise KeyError(key)
    KeyError: 'GFORTRAN_LIB'
```

**Comment by grburgess** [comment]
I agree. There must be a better way to deal with this dependency. Outside of home-brew... is there any reason to keep fortran in a different place?

**Comment by giacomov** [comment]
@grburgess : can you test the setup I just committed on your mac?

I cleaned up a lot the setup and made it way more streamlined. In principle it should work now. The principle is, if Xspec is able to run (which means that the libraries are either in LD_LIBRARY_PATH/DYLD_LIBRARY_PATH or somewhere in the system where ld can find them), then the functions I wrote should be able to find them.

Let me know how it goes.

**Comment by grburgess** [comment]
it installed ok on my mac.

I have this at the top of the log:


```
Found library XSFunctions in None
Found library XSModel in None
Found library XSUtil in None
Found library XS in /usr/local/heasoft-6.19/x86_64-apple-darwin15.5.0/lib
Found library cfitsio in None
Found library CCfits_2.5 in /usr/local/heasoft-6.19/x86_64-apple-darwin15.5.0/lib
Found library wcs-4.20 in /usr/local/heasoft-6.19/x86_64-apple-darwin15.5.0/lib
Found library gfortran in None

```

**Comment by giacomov** [comment]
Thanks! Looks good. The None means that the library is in some of the system paths, so the linker will find it without any further addition. When there is a path instead, it means that it needs to be passed in a -L flag to the linker. It's explained in the comments in setup.py if you want to go deeper.

If a library is not found anywhere you will get an exception. You can try by yourself unsetting the DYLD_LD_LIBRARY, so that it will not find the libraries in heasoft anymore.

**Pull request merged**
