### PR TITLE
1D templates were failing. added np.atleast_1d to fix

### PR DESCRIPTION
**Pull request by grburgess**
I noticed that 1D template models were failing due to a map. I added a check to expand the dimension as needed.

### CODE REVIEW

**Comment by giacomov** [comment]
So this was happening with one dimensional parameter spaces right?

I am trying to figure out why the tests didn't catch this problem...

**Comment by grburgess** [comment]
I meant to add a test. It's because in the tests the model has more than one parameter. I was going to add a one parameter test, but got caught up.

**Comment by grburgess** [comment]
I'm adding a test. You can then try it to see if the problem

**Comment by giacomov** [comment]
Thanks!

**Pull request merged**
