### PR TITLE
Simon edit model.link

### PR DESCRIPTION
**Pull request by ssteinmassl**
parameter_1 in link function can be either a single object or a list

### CODE REVIEW

**Comment by grburgess** [comment]
@ssteinmassl just a reminder. Please write some tests for these additions and perhaps provide an example so that it can be included in the documentation. thanks for taking this on!

**Comment by giacomov** [comment]
Thanks for doing this!

A suggestion: you can do this at the beginning:

```python
if not isinstance(parameter_1,list):
    # Make a list of one element
    parameter_1_list  = [parameter_1]
else:
    # Make a copy to avoid tampering with the input
    parameter_1_list = list(parameter_1)
```

From that moment on you can work with the list (which might be of one element) and avoid all code duplication.

**Comment by ssteinmassl** [comment]
updated model.link as suggested and  model.unlink as well to allow for a list of parameters there as well. Further added some lines to test_links in test_model.py in order to test for a list of paramters as input in linking and unlinking as well

**Comment by giacomov** [comment]
awesome! Thank you very much,

**Pull request merged**
